### PR TITLE
add window.event in onKey

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
This port dae/anki@ddb4db0c9618d67d22a35bd7eb1baf664a3d2f6d
It's related to the fact that now, onKey expect an event.

And it'll make disappear the line "JS error on line 40: Uncaught
TypeError: Cannot read property 'which' of undefined" which keeps
popping when I run anki in a terminal with your addon

#### Description

*Concisely describe what the pull request is trying to achieve. If pertinent, link to an existing issue report, or briefly explain the problem the PR is meant to solve. Feel free to attach screenshots or other media for UI-related changes.*

#### Checklist:

*Please replace the space inside the brackets with an **x** and fill out the ellipses if the following items apply:*

- [ ] I've read and understood the [contribution guidelines](./CONTRIBUTING.md)
- [x] I've tested my changes against at least one of the following [Anki builds](https://apps.ankiweb.net/#download):
  - [x] Latest standard Anki 2.1 binary build [required for Anki-compatible 2.1 add-ons]
  - [ ] Latest alternative Anki 2.1 binary build
  - [ ] Latest Anki 2.0 binary build [required for Anki 2.0-compatible add-ons]
- [x] I've tested my changes on at least one of the following platforms:
  - [x] Linux, version:
  - [ ] Windows, version:
  - [ ] macOS, version: 
- [ ] My changes potentially affect non-desktop platforms, of which I've tested:
  - [ ] AnkiMobile, version:
  - [ ] AnkiDroid, version:
  - [ ] AnkiWeb

### CODE REVIEW

**Comment by Arthur-Milchior** [comment]
There are no contribution guidelines here

**Comment by Arthur-Milchior** [comment]
Your add-on was incompatible with my add-on to resize-image. Calling the method to reload notes broke the resizing process.
I changed your add-on, so that instead of loading entirely the note again, the image/title is changed in javascript. This means that it does not interact anymore anything; except maybe if other add-on deal with the frozen status, but I don't now any such add-on.

Can you please tell me whether you'll consider my PR or whether I should share this modified version on my side (I'll still credit you and Tiago Barroso of course)

I also moved the js outside of the python, so that the file is more easy to read. I didn't change it entirely; in particular I still use %s for formatting, in order to minimize code change

**Comment by glutanimate** [comment]
Thanks, Arthur. This sounds good. I'm not at home atm, so I can't check, but: Have you tested if these changes work fine on 2.1.15? The large majority of Anki users are still on <2.1.17, so it would be beneficial to maintain compatibility (ideally without having to push a separate AnkiWeb branch for older releases).

My other question (once again, without access to my dev machine until later this evening) would be: Have you noticed any pop ins or elements shifting around while the editor loads? There's another older open PR that switched to JS to update the icons, but it would cause the view to flicker on toggling the icons.

**Comment by Arthur-Milchior** [comment]
I've not tested with .15. However, I really don't use anything that was not already in 2.0. I just use a little bit of jQuery. So I have little doubt it'll will work. It's not like I was using the new features you added for .21
There is no flickr I can see

**Comment by Arthur-Milchior** [comment]
This version of the add-on works with .15
My add-on does not, but I only promised it to be compatible with current version

**Comment by glutanimate** [comment]
Thanks, Arthur. I can confirm that all appears to be working well on 2.1.15 and 2.1.20. Really nice job!

And congrats on reaching your funding goal for the image resizer add-on!

**Comment by glutanimate** [comment]
New release is now live as [2.1.0](https://github.com/glutanimate/frozen-fields/releases/tag/v2.1.0). If you could instruct your image resizer users to give it a try and let us know if there are any issues that would be very much appreciated. If the response is positive and there are no unforeseen problems I'll be happy to go ahead with the AnkiWeb release.

**Comment by Arthur-Milchior** [comment]
Thank you. 
I posted a message on the kickstarter, so that people see where to take 2.1.0 and test it. I hope someone will confirm it works for them

**Pull request merged**
