### PR TITLE
Fix extra td

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
#### Description

As you just show me recently, there is now a hook for bridge. I use it.
Since I know you prefer to have a single code for every version, I tested for version number. If it's >= 20, I use it. Otherwise I use the previous method.

#### Checklist:

*Please replace the space inside the brackets with an **x** and fill out the ellipses if the following items apply:*

- [ ] I've read and understood the [contribution guidelines](./CONTRIBUTING.md)
- [x] I've tested my changes against at least one of the following [Anki builds](https://apps.ankiweb.net/#download):
  - [x] Latest standard Anki 2.1 binary build [required for Anki-compatible 2.1 add-ons]
  - [ ] Latest alternative Anki 2.1 binary build
  - [ ] Latest Anki 2.0 binary build [required for Anki 2.0-compatible add-ons]
- [x] I've tested my changes on at least one of the following platforms:
  - [x] Linux, version:
  - [ ] Windows, version:
  - [ ] macOS, version: 
- [ ] My changes potentially affect non-desktop platforms, of which I've tested:
  - [ ] AnkiMobile, version:
  - [ ] AnkiDroid, version:
  - [ ] AnkiWeb

### CODE REVIEW

**Comment by Arthur-Milchior** [comment]
Do you prefer plenty of unrelated PR, or is it okay if all changes are in a single PR ?
Both commits are unrelated, but in order not to loose time, I clearly would prefer not to have to create multiple PR for small things

**Comment by glutanimate** [comment]
Generally I'd prefer changes to spread across multiple PRs if they concern unrelated issues. I would have been ok bundling them all together this once, but my problem right now is that I've just started on refactoring the add-on in the `develop` branch  – which makes it difficult to merge your changes.

How about this:

You could file a2ad43f (and any additional changes that qualify as hotfixes) against master, and rebase 9ccd7b4 against `develop` (I would then cherry-pick a2ad43f and any other potential hotfixes into `develop` on my end).

Once 9ccd7b4 is merged, please hold off for a bit on submitting additional refactoring PRs until  `develop` is merged back into `master` (i.e. my refactoring is done). Though if you stumble on any regressions that need to be addressed with smaller hotfixes, I'll be happy to merge them into `master` of course, and push out corresponding FF 2.1.x patch releases

`develop` will be targeting Anki 2.1.21+, and likely be released as FF 3.x, so this is more of a long-term project.

**Comment by Arthur-Milchior** [comment]
This PR now only contains the hotfix removing the extra TD

**Comment by glutanimate** [comment]
Thanks!

**Pull request merged**
